image: hseeberger/scala-sbt:16.0.1_1.5.5_3.0.1

stages:
  - test

before_script:
  - sbt sbtVersion
  - sbt update

test:
  stage: test
  script:
    - SBT_OPTS="-Xss1024M" sbt clean test -DSTURDY_DEBUG_FIXPOINT="false"
