/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class fenv_FEnv */

#ifndef _Included_fenv_FEnv
#define _Included_fenv_FEnv
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     fenv_FEnv
 * Method:    getRoundingMode
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_fenv_FEnv_getRoundingMode
  (JNIEnv *, jclass);

/*
 * Class:     fenv_FEnv
 * Method:    setRoundingMode
 * Signature: (I)V
 */
JNIEXPORT void JNICALL Java_fenv_FEnv_setRoundingMode
  (JNIEnv *, jclass, jint);

/*
 * Class:     fenv_FEnv
 * Method:    FE_TONEAREST
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_fenv_FEnv_FE_1TONEAREST
  (JNIEnv *, jclass);

/*
 * Class:     fenv_FEnv
 * Method:    FE_DOWNWARD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_fenv_FEnv_FE_1DOWNWARD
  (JNIEnv *, jclass);

/*
 * Class:     fenv_FEnv
 * Method:    FE_UPWARD
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_fenv_FEnv_FE_1UPWARD
  (JNIEnv *, jclass);

/*
 * Class:     fenv_FEnv
 * Method:    FE_TOWARDZERO
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_fenv_FEnv_FE_1TOWARDZERO
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
