name: Compile

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22
      - uses: DeterminateSystems/magic-nix-cache-action@v14 # v14
      - name: Check Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@v13 # v13

      - name: Compile via Nix shell command
        run: nix develop .#ci -c ci-compile
