name: Compile

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  compile:
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22
      - uses: DeterminateSystems/magic-nix-cache-action@v14 # v14
      - name: Check Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@v13 # v13

      - name: Build sturdy via Nix
        run: nix build .#sturdy

  docker:
    runs-on: ubuntu-latest
    needs: compile
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22
      - uses: DeterminateSystems/magic-nix-cache-action@v14 # v14
      - name: Check Nixpkgs inputs
        uses: DeterminateSystems/flake-checker-action@v13 # v13

      - name: Build docker image
        run: nix build .#docker
